addons:
  sonarqube: true
env:
  global:
    secure: Awmb5NwHRKkoikK/CR7r5849hyBo/M7qhdpqPZbd8RIdV7EGxeoCasPa46SnHWqCWs7QREjU7QnciHjcaUsVdIjX7xRconrZj6tuv2UBwihc9MHxnafkcJECq2XQczFo4GN0eMWzoVKxg8HwbhtRexI/mZXBIzTQ/j8EakKF+PzsVW8TSfBeTsKZb4UAuqcgS4oYcNAn0ZVZ4tCm9qb6nVq5y9NRbSbOSIRMVchfYT7hVsYQhJLkgCaURS0gb8OaW5RPvaMb3h84s+mZ08fPVeZnPkkRpDOElW/wTZ5Jj3CNnBAiHB9aEys/m3lT3QWxVcXoo8w12Ki7IYH1ElOA5zzrZJniqTQfQ8Inj/xfJtbVX0io1P2O0d4uqIvcwrYonb1RKleU09SqvwXZsPgduDB3s28qrNvoUHtUKc+ptUXQEXX2inKayohDhfKhf2kk/xYvra4dRY19d7Ths1Oq4rzwKoqc1dVsacR4kn+qn9EZSYbASoOYNYMYMwiKARRkjZlTooZRn7WtTJwPet+RSpCKGC0HITaF78kVHtE+1aXOyFH8n88Fm8NT4nRDyfu8++4/4JqPl0vgJal7SxWvQC6FJD3OJk5GmbNHdFYaeVpruK0T/AcgIJcQdpw7qKMDjMdX2g0KZwReaS/vgVDLDICwjc277pXvtm4lpyqeLho=
language: java
jdk:
- oraclejdk8
script: mvn -f sandbox/dominio/pom.xml clean package coveralls:report sonar:sonar -P cobertura -Dsonar.login=$SONAR_TOKEN
